version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: config
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ticketing-net

  backend:
    build:
      context: ./Server
    container_name: backend-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/config
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - ticketing-net

  frontend:
    build:
      context: ./client/Ticketing_application
    container_name: frontend-app
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - ticketing-net

volumes:
  mysql-data:

networks:
  ticketing-net:
